name: Beta Build

on:
  push:
    branches:
      - '**'
    branches-ignore: 
      - 'main'
      - 'master'

  workflow_dispatch: 
    inputs: 
      branch:
        description: 'Branch to build'
        required: true 
        type: string
jobs:
  call-workflow:
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-betabuilds.yml@main
    secrets: inherit
    with: 
      branch: ${{ inputs.branch }}


