name: Beta Build

on: [push, workflow_dispatch]

jobs:
  call-workflow:
    permissions:
      contents: read
      pull-requests: write
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-betabuilds.yml@main
    with: 
      branch: ${{ inputs.branch }}


