name: Beta Build

on:
  push:
    branches-ignore:   
      - main

env:
  call-workflow:
    permissions:
      contents: read
    pull-requests: write
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-betabuilds.yml@main
