name: Beta Build

on: [push, workflow_dispatch]

jobs:
  call-workflow:
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-betabuilds.yml@main
    secrets: inherit
    with: 
      branch: ${{ inputs.branch }}


